# Generated by Django 2.2.8 on 2020-01-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll', models.IntegerField(unique=True)),
                ('student_fname', models.CharField(max_length=100)),
                ('student_lname', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=20)),
                ('student_section', models.CharField(max_length=20)),
                ('telugu', models.IntegerField()),
                ('hindi', models.IntegerField()),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('social', models.IntegerField()),
            ],
        ),
    ]
